[tool.poetry]
name = "CovidPlot"
version = "0.1.0"
description = ""
authors = ["PythonForChange <eanorambuena@uc.cl>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.2.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
